test:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: mongoid_tags_arent_hard_test
      hosts:
        - localhost:27017
